### ISSUE TITLE
Process cannot be started exception

### ISSUE THREAD

**Issue by PeeHaa** [amphp/parallel-functions#12]
I suspect this is actually rather an `amp/process` issue instead, but this is where I found it.

OS: `Windows`  
PHP version: `PHP 7.2.2 (cli) (built: Jan 31 2018 19:31:17) ( ZTS MSVC15 (Visual C++ 2017) x64 )`  
Driver: `native`  
Package versions:

amphp/amp `v2.0.7`
amphp/byte-stream `v1.5.0`
amphp/parallel  `v1.0.1`
amphp/parallel-functions `v0.1.3`
amphp/parser `v1.0.0`
amphp/process ` v1.0.0`
amphp/sync `v1.0.1`

Repro:

```php
\Amp\Loop::run(function() {
    yield \Amp\ParallelFunctions\parallel(function() {
        return password_verify('foo', 'bar');
    })();
});
```

Error:

    $ php example/test.php

> PHP Fatal error:  Uncaught Amp\Process\StatusError: Process has not been started or has not completed starting. in D:\Web\HarmonyIO\Validation\vendor\amphp\process\lib\Process.php:239
> Stack trace:
> #0 D:\Web\HarmonyIO\Validation\vendor\amphp\parallel\lib\Context\Process.php(190): Amp\Process\Process->getStdin()
> #1 [internal function]: Amp\Parallel\Context\Process->Amp\Parallel\Context\{closure}()
> #2 D:\Web\HarmonyIO\Validation\vendor\amphp\amp\lib\Coroutine.php(74): Generator->send(3992)
> #3 D:\Web\HarmonyIO\Validation\vendor\amphp\amp\lib\Internal\Placeholder.php(127): Amp\Coroutine->Amp\{closure}(NULL, 3992)
> #4 D:\Web\HarmonyIO\Validation\vendor\amphp\amp\lib\Coroutine.php(79): Amp\Coroutine->resolve(3992)
> #5 D:\Web\HarmonyIO\Validation\vendor\amphp\amp\lib\Internal\Placeholder.php(127): Amp\Coroutine->Amp\{closure}(NULL, 3992)
> #6 D:\Web\HarmonyIO\Validation\vendor\amphp\amp\lib\Deferred.php(41): class@anonymous->resolve(3992)
> #7 D:\Web\HarmonyIO\Validation\vendor\amphp\process\lib\Internal\Windows\SocketConnector.php(260): Am in D:\Web\HarmonyIO\Validation\vendor\amphp\parallel\lib\Context\Process.php on line 195

**Comment by trowski** [comment]
Can you test with master of `amphp/process`?

**Comment by PeeHaa** [comment]
When adding ` yield \Amp\Parallel\Worker\pool()->shutdown();` to the end of the loop it's working as expected.

**Comment by PeeHaa** [comment]
Some more test info.

Running the tests in `amphp/process` they all work: https://gist.github.com/PeeHaa/3cfe9a667243f2a53138d368bae30ee6

Running the tests in `amphp/parallel` I get several "PHP Fatal error:  Uncaught Amp\Process\StatusError: Process has not been started or has not completed starting." errors: https://gist.github.com/PeeHaa/5597d20bc7795573aec5451b896d6264

> PHP Fatal error: Uncaught Amp\Process\StatusError: Process has not been started or has not completed starting. in D:\Web\playground\trowski\parallel\vendor\amphp\process\lib\Process.php:239

**Comment by PeeHaa** [comment]
After running the `amphp/parallel` tests with the fixed process checkout the only thing that fails (hangs) is `$ php examples/worker-pool-simple.php`: https://gist.github.com/PeeHaa/5597d20bc7795573aec5451b896d6264

**Comment by PeeHaa** [comment]
Small update after some more debugging.

`amphp\process\lib\Internal\Windows\Runner.php:91` starts the process, but there is never a `proc_close` which kills it again.

**Comment by trowski** [comment]
Fixed by removing a call to `stream_get_contents` that was hanging in the Windows process runner in `amphp/process`.
