### ISSUE TITLE
Unable to make it work with CodeIgniter 3, getting warnings

### ISSUE THREAD

**Issue by sayanb** [amphp/parallel-functions#13]
I am trying to use this with CodeIgniter 3, with 

`require './vendor/autoload.php';`

in my index.php

My code:

```
<?php 

use function Amp\ParallelFunctions\parallelMap;
use function Amp\Promise\wait;

class Paralleltest extends CI_Controller {
    
    public function receive() {
        error_log("Parent, starting " . getmypid());

        try {
            $responses = wait(parallelMap([
                'https://google.com/',
                'https://github.com/',
                'https://stackoverflow.com/',
            ], function ($url) {
                return $this->executeTask($url);
            }));
        } catch (Exception $ex) {
            //print_r($ex->getReasons());
            error_log($ex->getMessage());
            exit;
        }

        error_log("Parent, got everything " . getmypid());
    }

    public function executeTask($url) {
        error_log("Getting $url in child " . getmypid());
        return file_get_contents($url);
    }
}
```

When I try to run this from the command line, it seems executeTask() never gets called, and I get the following issues:

_PHP Warning:  Class 'Paralleltest' not found in /home/sayan/Documents/Programming/farmer-giles/vendor/opis/closure/src/SerializableClosure.php on line 232
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /home/sayan/Documents/Programming/farmer-giles/vendor/opis/closure/src/SerializableClosure.php on line 109
PHP Warning:  Class 'Paralleltest' not found in /home/sayan/Documents/Programming/farmer-giles/vendor/opis/closure/src/SerializableClosure.php on line 232
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /home/sayan/Documents/Programming/farmer-giles/vendor/opis/closure/src/SerializableClosure.php on line 109
PHP Warning:  Class 'Paralleltest' not found in /home/sayan/Documents/Programming/farmer-giles/vendor/opis/closure/src/SerializableClosure.php on line 232
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /home/sayan/Documents/Programming/farmer-giles/vendor/opis/closure/src/SerializableClosure.php on line 109_

Any help would be greatly appreciated.

**Comment by kelunik** [comment]
Your class needs to be autoloadable by Composer, which currently doesn't seem to be the case.

**Comment by sayanb** [comment]
I refactored the code a bit, to the following:

Controller:

```
<?php 

class Paralleltest extends CI_Controller {
    
    public function receive() {        
        $this->paralleltasks->runTask();
    }
}
```

Then I moved most of the code to a library called Paralleltasks:

```
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

use function Amp\ParallelFunctions\parallelMap;
use function Amp\Promise\wait;

class Paralleltasks {

	public function runTask() {
		error_log("Parent, starting " . getmypid());
		try {
                     $responses = wait(parallelMap([
                        'https://google.com/',
                        'https://github.com/',
                        'https://stackoverflow.com/',
                     ], function ($url) {
                        error_log("In child " . get_class($this));
                        $this->executeTask($url);
                  }));
                }  catch (Exception $ex) {
                        //print_r($ex->getReasons());
                       error_log($ex->getMessage());
                       exit;
                }
                error_log("Parent, got everything " . getmypid());
	}

	public function executeTask($url) {
                error_log("Getting $url in child " . getmypid());
                return file_get_contents($url);
        }

}
```

The library Paralleltasks, which has all the code from amphp/parallel-functions is **auto-loadable**, using CodeIgniter's recommended auto-loading system:

[Auto-loading Resources in CodeIgniter 3](https://www.codeigniter.com/user_guide/general/autoloader.html)

However, now the warnings come from this auto-loaded library:

_Parent, starting 9432
PHP Warning:  Class 'Paralleltasks' not found in /home/sayan/Documents/Programming/tests/vendor/opis/closure/src/SerializableClosure.php on line 232
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /home/sayan/Documents/Programming/tests/vendor/opis/closure/src/SerializableClosure.php on line 109
PHP Warning:  Class 'Paralleltasks' not found in /home/sayan/Documents/Programming/tests/vendor/opis/closure/src/SerializableClosure.php on line 232
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /home/sayan/Documents/Programming/tests/vendor/opis/closure/src/SerializableClosure.php on line 109
PHP Warning:  Class 'Paralleltasks' not found in /home/sayan/Documents/Programming/tests/vendor/opis/closure/src/SerializableClosure.php on line 232
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /home/sayan/Documents/Programming/tests/vendor/opis/closure/src/SerializableClosure.php on line 109
Parent, got everything 9432_

@kelunik is Composer the only way to autoload this? Typically Composer is used to load third-party vendors, not code we write ourselves. Should the framework's own auto-loading feature work in theory? In that case, I might have to reach out to CodeIgniter's devs regarding this, unless you notice something!

**Comment by kelunik** [comment]
@sayanb It's the only autoloading mechanism supported out of the box, yes. If you want to use a different autoloader, you need to register it in the child processes somehow, e.g. by putting a `require_once` inside every closure you submit to the children.

**Comment by sayanb** [comment]
Doing this


   require_once(getcwd().'/application/libraries/Paralleltasks.php');

```
try {
    $responses = wait(parallelMap([
        'https://google.com/',
        'https://github.com/',
        'https://stackoverflow.com/',
    ], function ($url) {
            //Load the class in the child
            require_once(getcwd().'/application/libraries/Paralleltasks.php');
            error_log("In child " . get_class($this));
            $this->executeTask($url);
        }));
    }  catch (Exception $ex) {
        //print_r($ex->getReasons());
        error_log($ex->getMessage());
        exit;
    }
```

Doesn't seem to make the problem go away. I guess there are other dependencies of CodeIgniter, which needed to be loaded as well, for it to be able to properly instantiate the object, and composer is probably the only way.

**Comment by kelunik** [comment]
@sayanb Sorry for the bad advice, it obviously doesn't work that way, because the task class needs to exist before / when the callable is unserialized.

@trowski Maybe you have a better advice how to use a custom autoloader? A custom `Environment` maybe?

**Comment by trowski** [comment]
Yes, a custom `Environment` that includes the required files when the object is built would be the easiest solution.

```php
class AutoloadingEnvironment implements Environment
{
    private $environment;

    public function __construct()
    {
        (function () { // Protect scope
            require 'path/to/autoload.php';
        })();

        $this->environment = new BasicEnvironment;
    }
    
    // Other required methods
}

class CustomWorkerFactory implements WorkerFactory
{
    public function create(): Worker
    {
        return new WorkerProcess(AutoloadingEnvironment::class);
    }
}
```

You'll need to define these classes, create an instance of `DefaultPool` using an instance `CustomWorkerFactory`. You can then use this `Pool` instance with `parallel()` or you can use it as the global worker pool by passing it to `Amp\Parallel\Worker\pool()`, which `parallel()` automatically uses if no `Pool` instance is given.

**Comment by kelunik** [comment]
In that case `AutoloadingEnvironment` must still be autoloadable via Composer.

**Comment by trowski** [comment]
Based on the stack trace above, it looks like composer is being used as well. @sayanb I'm guessing you generally include both the composer and CodeIgniter autoloader?

**Comment by kelunik** [comment]
There hasn't been any further activity, so I'm closing this issue. Please comment with further information, we can always reopen the issue.
