### ISSUE TITLE
Uncaught Error in worker with message "Class 'common\models\Sha256Block' not found" and code "0"; use Amp\Parallel\Worker\TaskError::getWorkerTrace() fo r the stack trace in the worker

### ISSUE THREAD

**Issue by s-fog** [amphp/parallel-functions#15]
Hi guys. Please help me. Use example of ur script.
`Promise\wait(parallelMap([0, 1, 2], function ($part)) {
                new \common\models\Sha256Block;
            }));`
And i catch this problem. Read all what i can. I cant connect Class into this function. Who knows issue?

**Comment by kelunik** [comment]
There hasn't been any further activity, so I'm closing this issue. Please comment with further information, we can always reopen the issue.
