### ISSUE TITLE
Question: how to specify concurrency

### ISSUE THREAD

**Issue by freekmurze** [amphp/parallel-functions#2]
This seems like a very nice package, thank you!

Will this work on array with for instance 1 000 000 elements? Is there a way to specify the maximum concurrent processes?

**Comment by kelunik** [comment]
Currently this library uses the default process pool of `amphp/parallel`, which can be set using [`Amp\Parallel\Worker\pool()`](https://github.com/amphp/parallel/blob/074e2f215f7311890be539ce44b2436487f20413/lib/Worker/functions.php#L11-L30). [The default maximum is 32 workers.](https://github.com/amphp/parallel/blob/074e2f215f7311890be539ce44b2436487f20413/lib/Worker/Pool.php#L10)

I already thought about adding an optional parameter to `parallel()` that allows passing a custom pool, but decided to wait until there's a need.

Hope this answers your questions! If not, feel free to respond or create new issues for new questions. :+1:
