### ISSUE TITLE
docs/asset file points to non existing file/folder

### ISSUE THREAD

**Issue by sci3ma** [amphp/parallel-functions#23]
v1.0.0
`docs/asset` file points to `.shared/asset` which does not exist. `.shared/asset` seems to be outside of the lib.
It makes failing my deployment flow because my strict policy checks permissions of all files.
Besides that `.shared/` folder is empty after installing the library.

**Comment by rybakit** [comment]
@sci3ma See https://github.com/amphp/byte-stream/issues/48.

**Comment by sci3ma** [comment]
Thanks @rybakit but unfortunately I'm not sure how it should help me.

**Comment by kelunik** [comment]
@sci3ma it removes the symlink from the release archives, so it prevents the issue you're seeing.

The directory is empty, because it's a git submodule.

**Comment by rybakit** [comment]
@sci3ma Just create a PR with a fix like in https://github.com/amphp/byte-stream/commit/6bbfcb6f47e92577e739586ba0c87e867be70a23 and ask @kelunik to merge it and tag a new release :)

**Comment by sci3ma** [comment]
@rybakit Couldn't you start with that answer at the beginning? :D thanks for your help. PR created https://github.com/amphp/parallel-functions/pull/24
