### ISSUE TITLE
Custom Functions Issue

### ISSUE THREAD

**Issue by hemal8976** [amphp/parallel-functions#26]
I have added functions file to composer autoload  files and i am able to call custom function (user defined function) with `Worker\enqueueCallable('myFunction',$arg1,$arg2,$arg3);`

But inside myFunction code, i am unable to call php core functions like `milliseconds()`. How will i be able to use it?

**Comment by kelunik** [comment]
milliseconds isn't a core function, where does it come from?

**Comment by hemal8976** [comment]
> milliseconds isn't a core function, where does it come from?

Sorry my misunderstanding. Ignore this.
Thanks for help
