### ISSUE TITLE
how can i free memory

### ISSUE THREAD

**Issue by kinimodmeyer** [amphp/parallel-functions#27]
hello together,

when i have the following my memory is constantly fill even without the use of the array "$promises".

```
echo memory_get_usage(true);
for($i=0; $i < 5000;$i++) {
   self::$promises[] = parallel (function() use ($options, $record) {
          // call to aws lib
    })()
    echo memory_get_usage(true);
}
echo memory_get_usage(true);
```

how can i free the memory in my process?
after a while i need to clean-up the memory like the executed "parallel" methods.

**Comment by kelunik** [comment]
What do you mean with "without the use of the array `$promises`"? If you store them all in a static variable, memory won't be freed. You'll need to clear the array entries at some point.

**Comment by kinimodmeyer** [comment]
thanks for your fast awnser!


my worker crashed because out of memory (not related to the array promises):

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 49152 bytes) in .../vendor/amphp/parallel/lib/Worker/TaskWorker.php on line 111
```

i realized that when i add something like that on every 1000 calls the internals of amp/parallel get freed up:

```
Promise\wait(Promise\all(...))
```

i hope i have no memory problems no anymore, else i will open again, thanks!
