### ISSUE TITLE
How to call different functions?

### ISSUE THREAD

**Issue by ttodua** [amphp/parallel-functions#28]
In the examples, there are only given "simple function use-cases", like "sleep", "var_dump", etc... But what is an example, to call several different functions with parallelmap?  i.e. I want to fire 3 different functions (with different arguments) in parallel,  `f1("Italy")` ,  `f2("France")` ,  `f3("Finland")`  ?

**Comment by kelunik** [comment]
You can use `parallel()` and invoke them.

```php
$f1 = parallel('f1');
$f2 = parallel('f2');
$f3 = parallel('f3');

wait(all([$f1('Italy'), $f2('France'), $f3('Finland')]));
```

**Comment by ttodua** [comment]
Thanks!

**Comment by ttodua** [comment]
might be good if that was included in examples too.

**Comment by kelunik** [comment]
@ttodua Sure, please send a pull request to add a useful example!
