### ISSUE TITLE
parallelMap is not working inside class

### ISSUE THREAD

**Issue by haffoudhi** [amphp/parallel-functions#33]
I tried the provided examples inside a class, but parallelMap is returning null all the time. I moved the same code outside class, and it worked as expected. How can I make it work inside a class?

PHP version: 7.4
OS: windows 10

![Capture](https://user-images.githubusercontent.com/4338823/184876274-80f02e94-6f9e-4135-8933-64942c2f2fee.JPG)
![Capture](https://user-images.githubusercontent.com/4338823/184862713-25c7a325-3039-4233-93ec-00c0ba9c699b.JPG)
![Capture](https://user-images.githubusercontent.com/4338823/184878554-83928ced-f378-4ffd-97ef-08e116ada107.JPG)

**Comment by kelunik** [comment]
Could you try declaring the closure as static as well? It's probably not properly serialized.

**Comment by haffoudhi** [comment]
Thanks for the reply, I removed static, same issue.

![Capture](https://user-images.githubusercontent.com/4338823/184923058-051f77f0-0541-4dba-8e24-edab414653ad.JPG)
![Capture](https://user-images.githubusercontent.com/4338823/184923367-31a959d7-15ac-49ad-8a01-91f29047a77f.JPG)

**Comment by kelunik** [comment]
Your example results in `PHP Warning:  Class "Test" not found in /Users/kelunik/PHP/amphp/parallel-functions/vendor/laravel/serializable-closure/src/Serializers/Native.php on line 193` for me, because the class is defined in a file that's not autoloaded and thus not available in the child. Could you please post your entire example as text instead of an image? Do you have `ext-parallel` installed?

**Comment by haffoudhi** [comment]
I didn't install ext-parallel.

```
require_once "../vendor/autoload.php";

use function Amp\ParallelFunctions\parallelMap;
use function Amp\Promise\wait;

class testClass {
	public function test()
	{
		$responses = wait(parallelMap([
			"https://google.com/",
			"https://github.com/",
			"https://stackoverflow.com/",
		], function ($url) {
			return $url;
		}));
		
		var_dump($responses);
	}
}

$class = new testClass;
$class-\>test();

$responses = wait(parallelMap([
    "https://google.com/",
    "https://github.com/",
    "https://stackoverflow.com/",
], function ($url) {
    return $url;
}));

var_dump($responses);
```

**Comment by kelunik** [comment]
It properly fails for me as expected with the explanation above.

```
PHP Warning:  Class "testClass" not found in /Users/kelunik/PHP/amphp/parallel-functions/vendor/laravel/serializable-closure/src/Serializers/Native.php on line 193
PHP Warning:  Class "testClass" not found in /Users/kelunik/PHP/amphp/parallel-functions/vendor/laravel/serializable-closure/src/Serializers/Native.php on line 193
PHP Warning:  Class "testClass" not found in /Users/kelunik/PHP/amphp/parallel-functions/vendor/laravel/serializable-closure/src/Serializers/Native.php on line 193

Fatal error: Uncaught Amp\MultiReasonException: Multiple errors encountered; use Amp\MultiReasonException::getReasons() to retrieve the array of exceptions thrown in /Users/kelunik/PHP/amphp/parallel-functions/src/functions.php:59
```

I'm testing on PHP 8.1, because I can't compile PHP 7.4 due to incompatibilities right now, but I expect the results to be the same.

Please try moving your class definition to a file that's autoloaded.

**Comment by haffoudhi** [comment]
I moved the class "testClass" to file that's autoloaded, it is working fine now. @kelunik, thank you for your help.

**Comment by kelunik** [comment]
It's still weird that you don't get a proper error message, but I'm glad it's working fine now. :-)
