### ISSUE TITLE
Support for AMP v3

### ISSUE THREAD

**Issue by stof** [amphp/parallel-functions#35]
This package does not have a version compatible with AMP v3 yet. It would be great to have one.

**Comment by trowski** [comment]
No AMPHP v3 compatible version of this package is planned. Serializing closures is too fragile and was meant to be experimental more than something actually used in production. Use the `Task` interface in `amphp/parallel` instead.

**Comment by kelunik** [comment]
@trowski I don't see a reason to avoid providing this package in an Amp v3 compatible version.

**Comment by trowski** [comment]
I'm still not a fan of serializing code + data rather than serializing data only. Upgrading the library should be trivial, so if you still want want to support it we can certainly do that.

**Comment by stof** [comment]
I'm closing this as my interest was to allow grumphp to upgrade to AMP v3 and they got rid of this dependency.

**Comment by xtrime-ru** [comment]
Daniil once again helped a lot :)  https://github.com/amphp/parallel-functions/pull/36

**Comment by danog** [comment]
Can be closed now :)
