### ISSUE TITLE
Can't update package, dev-master is not a valid constraint

### ISSUE THREAD

**Issue by Silent0bserv3r** [amphp/parallel-functions#38]
Root composer.json requires amphp/parallel-functions dev-master, found amphp/parallel-functions[v0.1.0, v0.1.1, v0.1.2, v0.1.3, v1.0.0, v1.1.0, 1.x-dev, v2.0.0, 2.x-dev] but these do not match your constraint and are therefore not installable.

PHP version - 8.1.0
composer version -  2.5.4
`{
    "require": {
        "amphp/parallel-functions": "dev-master"
}`

**Comment by kelunik** [comment]
We switched to versioned branches, you can use `^1-dev` or `^2-dev` now if you really want to use unreleased versions. I'd strongly recommend to use the released versions instead.

**Comment by Silent0bserv3r** [comment]
When was dev-master constraint removed. we had this package for a long time in our composer.json but this is the first time we got this issue. It was added last year I think.

**Comment by kelunik** [comment]
Recently, as we merged https://github.com/amphp/parallel-functions/pull/36 and released v2.0.0. You can just update it to `^1` and should be fine.
