### ISSUE TITLE
How is it possible to parallelize file_get_contents?

### ISSUE THREAD

**Issue by Bilge** [amphp/parallel-functions#4]
Sorry for posting a question in your issue tracker, but I don't understand how the following is possible.

```php
$responses = wait(parallelMap([
    'https://google.com/',
    'https://github.com/',
    'https://stackoverflow.com/',
], function ($url) {
    return file_get_contents($url);
}));
```

I was told, in no uncertain terms, that such a thing would be impossible using async because `file_get_contents()` is, and always will be, a synchronous blocking operation. That is why [Artax](https://github.com/amphp/artax) was created. If this is no longer the case then this is a breakthrough, but if not, and this library is actually using threads instead of coroutines, I think this should be clearly stated in the readme to avoid confusion.

**Comment by joelwurtz** [comment]
Internally, it create php process (or thread depend on your php configuration) that execute this function, which have been serialized. I think the documentation is more clear about this here : https://amphp.org/parallel-functions/

**Comment by Bilge** [comment]
Oh I see, I thought Amp was all about coroutines, but nevertheless that is very clever and may indeed be some kind of breakthrough. 👍

**Comment by kelunik** [comment]
@Bilge Don't worry about questions in the issue tracker. Amp is mainly focused on non-blocking I/O, correct, but it can also do multi-processing. Consumers don't have to care, they get a promise either way. We also already used threading via `libuv` for filesystem access before.

Care to provide a PR to replicate the note from the docs into the README?

**Comment by Bilge** [comment]
Would love to, but if you observe my [contribution history](https://github.com/Bilge) you may notice I'm a little busy at the moment.
