### ISSUE TITLE
Loop exceptionally stopped in example

### ISSUE THREAD

**Issue by reimax** [amphp/parallel-functions#6]
Hi, my code:

```php
require_once 'vendor/autoload.php';

$responses = Amp\Promise\wait(Amp\ParallelFunctions\parallelMap([
    'https://google.com/',
    'https://github.com/',
    'https://stackoverflow.com/',
], function ($url) {
    return file_get_contents($url);
}));
```

get error: `Loop exceptionally stopped without resolving the promise`

how to fix?

**Comment by kelunik** [comment]
Which SAPI (Apache, FPM, CLI) do you use?

**Comment by reimax** [comment]
apache + php 7.1

**Comment by kelunik** [comment]
Please add the following to your code:

```php
define('STDERR', fopen('php://stderr', 'w'));
```

We will probably integrate something like the following into `amphp/byte-stream` soon.

```php
if (!defined('STDOUT')) {
    define('STDOUT', fopen('php://stdout', 'w'));
}

if (!defined('STDERR')) {
    define('STDERR', fopen('php://stderr', 'w'));
}
```

**Comment by kelunik** [comment]
https://github.com/amphp/byte-stream/releases/tag/v1.2.2 fixes this which can be pulled via `composer update`. Thanks for your report.
